In [1]:
# Load the source database
# Asign headers and build the dataframe

import pandas as pd
headers=["Title", "Author", "Pages", "Year", "Genres", "Rating", "Avr", "Link"]
df = pd.read_csv('goodreadsdb.csv', names=headers)

In [2]:
# Search for no title books

df.loc[(df['Title'] == "No encontrado") | (df['Title'] == ",,")]

Empty DataFrame
Columns: [Title, Author, Pages, Year, Genres, Rating, Avr, Link]
Index: []

In [3]:
# Search for no author books

df.loc[(df['Author'] == "No encontrado") | (df['Author'] == ",,")]

Empty DataFrame
Columns: [Title, Author, Pages, Year, Genres, Rating, Avr, Link]
Index: []

In [4]:
# Search for no pages books

df.loc[(df['Pages'] == "No encontrado") | (df['Pages'] == ",,")]

,Title,Author,Pages,Year,Genres,Rating,Avr,Link
690,Brainwalker,Robyn Mundell,No encontrado,2016,"['fantasy', 'young-adult', 'childrens', 'child...",21809,4.36,http://www.goodreads.com/book/show/30346601-br...
1111,Pleasant Day,Vera Jane Cook,No encontrado,2015,"['contemporary', 'drama', 'book-club', 'fictio...",5688,4.32,http://www.goodreads.com/book/show/44575575-pl...
1421,"Karolina Dalca, Dark Eyes",M.R. Noble,No encontrado,2020,"['novels', 'fiction', 'drama', 'contemporary',...",6804,4.27,http://www.goodreads.com/book/show/55605912-ka...
1432,Dueling Fates,Stephanie M. Allen,No encontrado,2020,"['epic', 'novels', 'drama', 'fiction', 'contem...",6346,4.30,http://www.goodreads.com/book/show/54331802-du...
1438,Tooth for Tooth,J.K. Franko,No encontrado,2020,"['fiction', 'novels', 'drama', 'contemporary',...",6219,4.31,http://www.goodreads.com/book/show/52117056-to...
...,...,...,...,...,...,...,...,...
9814,White Knight Dom Academy,Lucian Bane,No encontrado,2014,[],347,4.49,http://www.goodreads.com/book/show/23494875-wh...
9820,Crash Lane News,CrashLaneNews.com,No encontrado,2015,"['contemporary', 'adult', 'education', 'new-ad...",140,4.30,http://www.goodreads.com/book/show/30109629-cr...
9822,The Overdue Life of Amy Byler,Kelly Harms,No encontrado,2019,"['fiction', 'romance', 'womens-fiction', 'chic...",89230,3.83,http://www.goodreads.com/book/show/41723475-th...
9858,Imitatore (The Donna Chronicles #1),A. Rose,No encontrado,2018,"['fantasy', 'young-adult', 'adventure', 'adult...",151,4.19,http://www.goodreads.com/book/show/38592955-im...
9994,The New Oxford American Dictionary,Oxford University Press,No encontrado,1962,"['reference', 'reference', 'dictionaries', 'no...",9033,3.79,http://www.goodreads.com/book/show/18715598-th...

In [5]:
# Search for no published date books

df.loc[(df['Year'] == "No encontrado") | (df['Year'] == ",,")]

,Title,Author,Pages,Year,Genres,Rating,Avr,Link
722,The Aeneid,Virgil,442,No encontrado,"['classics', 'poetry', 'fiction', 'fantasy', '...",110928,3.85,http://www.goodreads.com/book/show/12914.The_A...
1173,Metamorphoses,Ovid,723,No encontrado,"['classics', 'poetry', 'fantasy', 'mythology',...",60370,4.07,http://www.goodreads.com/book/show/1715.Metamo...
1772,Annabel Horton: Lost Witch of Salem,Vera Jane Cook,402,No encontrado,"['contemporary', 'epic', 'fantasy', 'paranorma...",280,4.32,http://www.goodreads.com/book/show/17899134-an...
2456,To Dream the Blackbane,Richard J. O'Brien,261,No encontrado,"['fiction', 'contemporary', 'novels', 'book-cl...",580,4.53,http://www.goodreads.com/book/show/43251704-to...
3112,Betrayal In Black,Mark M. Bello,No encontrado,No encontrado,"['contemporary', 'novels', 'epic', 'fiction']",929,4.39,http://www.goodreads.com/book/show/44597035-be...
4079,Letters from a Stoic,Seneca,256,No encontrado,"['philosophy', 'non-fiction', 'classics', 'his...",23893,4.35,http://www.goodreads.com/book/show/97411.Lette...
4115,Avaland,Amy Croucher Rose,342,No encontrado,[],26,4.73,http://www.goodreads.com/book/show/40273980-av...
7744,On the Shortness of Life,Seneca,106,No encontrado,"['philosophy', 'non-fiction', 'classics', 'sel...",21762,4.19,http://www.goodreads.com/book/show/97412.On_th...
8472,The Satyricon,Petronius,272,No encontrado,"['classics', 'fiction', 'poetry', 'literature'...",7278,3.80,http://www.goodreads.com/book/show/168214.The_...
8696,Night That Jimi Died,Darragh J Brady,175,No encontrado,[],36,4.89,http://www.goodreads.com/book/show/40580446-ni...
8897,Wuthering Heights by Emily Brontë,Hilda D. Spear,96,No encontrado,"['classics', 'fiction', 'romance', 'literature...",22600,4.12,http://www.goodreads.com/book/show/130346.Wuth...
9388,الشيخ زعرب وآخرون,يوسف السباعي,No encontrado,No encontrado,"['short-stories', 'fiction']",153,3.64,http://www.goodreads.com/book/show/2930763
9399,The Conquest of Gaul,Gaius Julius Caesar,269,No encontrado,"['history', 'classics', 'non-fiction', 'histor...",9768,3.99,http://www.goodreads.com/book/show/592167.The_...

In [6]:
# Get the no pages books to correct

nopages = df.loc[(df['Pages'] == "No encontrado") | (df['Pages'] == ",,")]
nopages.to_csv('nopages.csv', index=False, header=False)

In [7]:
# Get the no year books to correct

noyear = df.loc[(df['Year'] == "No encontrado") | (df['Year'] == ",,")]
noyear.to_csv('noyear.csv', index=False, header=False)